version: "3.8"

services:
  profile:
    image: repo.notavaa.com:5000/sol/profile:latest
    ports:
      - "7000:80"
    env_file:
      - ./.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - net1

  back:
    image: repo.notavaa.com:5000/sol/back:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - /srv/sol/uploads:/app/uploads
      - /srv/sol/results:/app/results
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - net1

networks:
  net1:
    external: true
