version: '3.8'

services:
  postgres:
    image: repo.notavaa.com:5000/postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net1
    env_file:
      - ./.env
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 60s
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq:
    image: repo.notavaa.com:5000/rabbitmq:4-management
    hostname: rabbitmq
    container_name: rabbitmq
    networks:
      - net1
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
volumes:
  postgres_data:
    external: false
networks:
    net1:
        external: true