version: "3.8"

services:
  profile:
    image: repo.notavaa.com:5000/sol/profile:latest
    env_file:
      - ./.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 3s
        order: start-first
    networks:
      - net1

  back:
    image: repo.notavaa.com:5000/sol/back:latest
    env_file:
      - ./.env
    volumes:
      - /srv/sol/uploads:/app/uploads
      - /srv/sol/results:/app/results
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 3s
        order: start-first
    networks:
      - net1
  sms-sender:
    image: repo.notavaa.com:5000/sol/sms-sender:latest
    env_file:
      - ./.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 3s
        order: start-first
    networks:
      - net1
networks:
  net1:
    external: true