version: "3.6"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.cert
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    volumes:
      - /root/registry_certs:/certs
      - /data/registry:/var/lib/registry
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - net1

  nexus:
    image: sonatype/nexus3:3.82.1-alpine
    environment:
      INSTALL4J_ADD_VM_PARAMS: >
        -Xms1024m -Xmx2048m -XX:MaxDirectMemorySize=2g
        -Djava.util.prefs.userRoot=/nexus-data/java-prefs
    volumes:
      - /srv/sol/nexus-data:/nexus-data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net1
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # کل دایرکتوری Nginx را به /etc/nginx می‌دهیم
      - /srv/sol/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/sol/nginx/configs:/etc/nginx/conf.d:ro
      - /srv/sol/nginx/certs:/etc/nginx/certs:ro
      - /srv/sol/nginx/logs:/var/log/nginx
      - /srv/sol/nginx/cache:/var/cache/nginx
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    networks:
      - net1


networks:
  net1:
    external: true
