version: "3.8"

services:
  nginx:
    image: repo.notavaa.com:5000/nginx:alpine
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - /srv/sol/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/sol/nginx/configs:/etc/nginx/conf.d:ro
      - /srv/sol/nginx/certs:/etc/nginx/certs:ro
      - /srv/sol/nginx/services:/etc/nginx/services.d:ro
      - /srv/sol/nginx/snippets:/etc/nginx/snippets:ro
      - /srv/sol/nginx/logs:/var/log/nginx
      - /srv/sol/nginx/cache:/var/cache/nginx
      - /srv/sol/uploads:/srv/sol/uploads:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      update_config:
          parallelism: 1
          delay: 5s
          order: start-first        
    networks:
      - net1

networks:
  net1:
    external: true
